#!/bin/sh
set -e

case "$1" in
    purge)
        # Remove data and config
        rm -rf /var/lib/vexilla
        rm -rf /etc/vexilla
        # Remove user
        deluser --quiet vexilla 2>/dev/null || true
        delgroup --quiet vexilla 2>/dev/null || true
        ;;
    remove)
        # Stop the service
        deb-systemd-invoke stop vexilla.service >/dev/null 2>&1 || true
        ;;
esac
